SEEDS = [
  {
    keyword: "Out of stock",
    urls: [
      'https://www.powdervalleyinc.com/product/6-1-2-small-rifle-remington-primer/',
      'https://www.powdervalleyinc.com/product/cci-400-small-rifle-primers-1000/',
      'https://www.powdervalleyinc.com/product/cci-41-5-56-military-primers/',
      'https://www.powdervalleyinc.com/product/cci-br4-small-rifle-benchrest-1000/',
      'https://www.powdervalleyinc.com/product/cci-aps-br4-small-rifle-benchrest-1000/',
      'https://www.powdervalleyinc.com/product/cci-aps-strips-400-small-rifle/',
      'https://www.powdervalleyinc.com/product/federal-205-small-rifle-primers-1000/',
      'https://www.powdervalleyinc.com/product/federal-gm100m-sm-pstl-match-1000/',
      'https://www.powdervalleyinc.com/product/rem-7-1-2-small-rifle-br-primer/',
      'https://www.powdervalleyinc.com/product/winchester-small-rifle-primers-1000/',
      'https://www.powdervalleyinc.com/product/winchester-small-rifle-match-primers-1000/',
      'https://www.powdervalleyinc.com/product/winchester-41-5-56-military-primers/',
      'https://www.midsouthshooterssupply.com/item/000200014/-number-500-small-pistol-primer-(1000-count)',
      'https://www.midsouthshooterssupply.com/item/00123wsr/winchester-small-rifle-primers-1000-count',
      'https://www.midsouthshooterssupply.com/item/00129200/magnum-small-pistol-primer-number-200-(1000-count)',
      'https://www.midsouthshooterssupply.com/item/0005022628/7-half-bench-rest-small-rifle-primer-(1000-count)',
      'https://www.midsouthshooterssupply.com/item/00350445smpcase/fiocchi-small-pistol-primers-12-and-000-count-case-(8-boxes-of-1500)',
      'https://www.midsouthshooterssupply.com/item/00350p0014c/-number-500-small-pistol-primer-5000-count-case',
      'https://www.midsouthshooterssupply.com/item/00129100/federal-small-pistol-primer-number-100-(1000-count)',
      'https://www.midsouthshooterssupply.com/item/00123wsp/winchester-small-pistol-primers-1000-count',
      'https://www.midsouthshooterssupply.com/item/000200017/-number-450-magnum-small-rifle-primer-(1000-count)',
      'https://www.midsouthshooterssupply.com/item/000200013/-number-400-small-rifle-primer-(1000-count)',
      'https://www.midsouthshooterssupply.com/item/00129gm205mar/gold-medal-ar-match-small-rifle-primer-number-gm205mar-(1000-count)',
      'https://www.midsouthshooterssupply.com/item/00129205/small-rifle-primer-number-205-(1000-count)',
      'https://www.midsouthshooterssupply.com/item/00350pwspc/winchester-small-pistol-primers-5000-count-case',
      'https://www.midsouthshooterssupply.com/item/00123wspm/winchester-small-pistol-magnum-primers-1000-count',
      'https://www.midsouthshooterssupply.com/item/00350p22600c/1-half-small-pistol-primer-5000-count-case',
      'https://www.midsouthshooterssupply.com/item/00350p0013c/-number-400-small-rifle-primer-5000-count-case',
      'https://www.midsouthshooterssupply.com/item/00123wmgsr/winchester-usa-ready-match-small-rifle-primers-1000-count',
      'https://www.midwayusa.com/product/1301332027',
      'https://www.midwayusa.com/product/1301776634',
      'https://www.midwayusa.com/product/2900166619',
      'https://www.midwayusa.com/product/953733657',
      'https://www.midwayusa.com/product/1301123611',
      'https://www.midwayusa.com/product/2900485932',
      'https://www.midwayusa.com/product/953676362',
      'https://www.midwayusa.com/product/1301264828',
      'https://www.midwayusa.com/product/953619121',
      'https://www.midwayusa.com/product/953198969',
      'https://www.midwayusa.com/product/1301170074',
      'https://www.midwayusa.com/product/1601120656',
      'https://www.midwayusa.com/product/1301810394',
      'https://www.midwayusa.com/product/2900117598',
      'https://www.midwayusa.com/product/953153612',
      'https://www.midwayusa.com/product/1013078964',
      'https://www.midwayusa.com/product/1301277952',
      'https://www.midwayusa.com/product/953179134',
      'https://www.midwayusa.com/product/1601371304',
      'https://www.midwayusa.com/product/1601162096',
      'https://www.midwayusa.com/product/1020691023',
      'https://www.midwayusa.com/product/1020691171',
      'https://www.natchezss.com/cci-standard-primers-500-small-pistol.html',
      'https://www.natchezss.com/winchester-small-rifle-primers.html',
      'https://www.natchezss.com/federal-premium-champion-centerfire-primers-small-pistol.html',
      'https://www.natchezss.com/cci-standard-primers-400-small-rifle.html',
      'https://www.natchezss.com/remington-centerfire-primers-5-1-2-small-pistol.html',
      'https://www.natchezss.com/winchester-primers-small-pistol-match-1000-ct.html',
      'https://www.natchezss.com/cci-standard-primers-34-large-7-62mm-military-nato-sensitivity-1000-ct.html',
      'https://www.natchezss.com/cci-aps-primers-mag-small-rifle.html',
      'https://www.natchezss.com/cci-aps-primers-mag-small-pistol.html',
      'https://www.natchezss.com/federal-premium-champion-centerfire-primers-mag-small-pistol.html',
      'https://www.natchezss.com/federal-premium-champion-centerfire-primers-small-rifle.html',
      'https://www.natchezss.com/cci-standard-primers-550-mag-small-pistol.html',
      'https://www.natchezss.com/winchester-small-pistol-primers.html',
      'https://www.natchezss.com/fiocchi-primers-small-rifle.html',
      'https://www.natchezss.com/cci-aps-primers-small-pistol.html',
      'https://www.natchezss.com/cci-aps-primers-small-rifle.html',
      'https://www.natchezss.com/federal-gold-medal-small-pistol-primer-1000-ct.html',
      'https://www.natchezss.com/fiocchi-primers-small-pistol.html',
      'https://www.natchezss.com/winchester-primers-small-rifle-match-1000-ct.html',
      'https://www.natchezss.com/cci-standard-primers-br4-small-rifle.html',
      'https://www.natchezss.com/remington-centerfire-primers-6-1-2-small-rifle.html',
      'https://www.natchezss.com/remington-centerfire-primers-1-1-2-small-pistol.html',
      'https://www.natchezss.com/cci-standard-primers-450-mag-small-rifle.html',
      'https://www.natchezss.com/federal-premium-gold-medal-centerfire-primers-small-rifle-match.html',
      'https://www.natchezss.com/remington-centerfire-primers-7-1-2-small-rifle-br.html',
      'https://www.natchezss.com/federal-gold-medal-centerfire-small-magnum-pistol-match-primer-200-cal-100-ct.html',
      'https://www.natchezss.com/cci-standard-primers-41-small-5-56mm-military-nato-sensitivity-1000-ct.html',
      'https://www.natchezss.com/federal-premium-gold-medal-centerfire-primers-ar-small-rifle-match.html',
      'https://www.armsunlimited.com/Sellier-Bellot-Small-Pistol-Primers-p/sbpr-sp.htm',
      # 'https://www.basspro.com/shop/en/winchester-magnum-small-pistol-primers',
      # 'https://www.basspro.com/shop/en/cci-primers-per-1000',
      # 'https://www.basspro.com/shop/en/federal-premium-gold-medal-match-primers',
      # 'https://www.basspro.com/shop/en/federal-champion-centerfire-primers',
      'https://www.outdoorlimited.com/accessories/reloading/primers/fiocchi-primers-small-pistol-445amp-1500-count/',
      'https://www.outdoorlimited.com/specials/closeout-items/remington-primers-5-1-2-small-pistol-x22626-1000-count/',
      'https://www.outdoorlimited.com/specials/rebate-center/cci-primed-for-action-rebate/cci-primers-no-500-small-pistol-0014-brick-of-1000-count/',
      'https://www.outdoorlimited.com/accessories/reloading/primers/unis-ginex-small-pistol-primers-5-000-count/',
      'https://www.outdoorlimited.com/specials/rebate-center/winchester-primer-rebate/winchester-primers-1-1-2-108-small-regular-pistol-wsp-1000-count/',
      'https://www.outdoorlimited.com/specials/rebate-center/winchester-primer-rebate/winchester-primers-1-1-2m-108-small-magnum-pistol-wspm-1000-count/',
      'https://www.precisionreloading.com/cart.php#!l=CCI&i=450',
      'https://www.precisionreloading.com/cart.php#!l=FD&i=P100',
      'https://www.precisionreloading.com/cart.php#!l=CCI&i=500',
      'https://www.precisionreloading.com/cart.php#!l=FD&i=P205M',
      'https://www.precisionreloading.com/cart.php#!l=WN&i=WSR',
      'https://www.precisionreloading.com/cart.php#!l=FD&i=P205',
      'https://www.precisionreloading.com/cart.php#!l=WN&i=WSP',
      'https://www.precisionreloading.com/cart.php#!l=RM&i=RAR75',
      'https://www.precisionreloading.com/cart.php#!l=CCI&i=400',
      'https://www.precisionreloading.com/cart.php#!l=FD&i=P200',
      'https://www.precisionreloading.com/cart.php#!l=CCI&i=41',
      'https://www.precisionreloading.com/cart.php#!l=FD&i=P205MAR',
      'https://www.precisionreloading.com/cart.php#!l=RM&i=RAR55',
      'https://www.precisionreloading.com/cart.php#!l=CCI&i=BR4',
      'https://www.precisionreloading.com/cart.php#!l=RM&i=RAR15',
      'https://www.precisionreloading.com/cart.php#!l=WN&i=WMGSP',
      'https://www.precisionreloading.com/cart.php#!l=WN&i=WMGSR',
      # 'https://reloadingunlimited.com/product/federal-small-pistol-magnum-200-primers-1000-count/',
      # 'https://reloadingunlimited.com/product/cci-small-rifle-primers-no-400-1000-count/',
      # 'https://reloadingunlimited.com/product/cci-aps-small-pistol-primers-strip-no-500-1000-count/',
      # 'https://reloadingunlimited.com/product/cci-aps-small-rifle-bench-rest-primers-strip-br4-1000-count/',
      # 'https://reloadingunlimited.com/product/cci-aps-small-rifle-primers-strip-no-400-1000-count/',
      # 'https://reloadingunlimited.com/product/cci-no-41-small-military-rifle-primers-1000-count/',
      # 'https://reloadingunlimited.com/product/cci-small-pistol-primers-no-500-1000-count/',
      # 'https://reloadingunlimited.com/product/federal-small-pistol-100-primers-1000-count/',
      # 'https://reloadingunlimited.com/product/federal-small-pistol-100m-gold-medal-match-primers-1000-count/',
      # 'https://reloadingunlimited.com/product/cci-small-rifle-magnum-primers-no-450-1000-count/',
      # 'https://reloadingunlimited.com/product/cci-small-rifle-benchrest-br4-primers-1000-count/',
      # 'https://reloadingunlimited.com/product/federal-small-rifle-205-primers-1000-count/',
      # 'https://reloadingunlimited.com/product/federal-small-pistol-magnum-match-primers-1000-count/',
      # 'https://reloadingunlimited.com/product/federal-small-rifle-205m-gold-medal-match-primers-1000-count/',
      # 'https://reloadingunlimited.com/product/federal-small-rifle-205m-gold-medal-match-primers-1000-count/',
      # 'https://reloadingunlimited.com/product/federal-small-rifle-ar-gm205mar-gold-medal-match-primers-1000-count/',
      # 'https://reloadingunlimited.com/product/remington-6-1-2-small-rifle-primers-1000-count/',
      # 'https://reloadingunlimited.com/product/remington-6-1-2-small-rifle-primers-1000-count/',
      # 'https://reloadingunlimited.com/product/remington-7-1-2-bench-rest-small-rifle-primers-1000-count/',
      # 'https://reloadingunlimited.com/product/remington-1-1-2-small-pistol-primers-1000-count/',
      # 'https://reloadingunlimited.com/product/remington-5-1-2-small-pistol-magnum-primers-1000-count/',
      # 'https://reloadingunlimited.com/product/winchester-small-pistol-magnum-primers-1000-count/',
      # 'https://reloadingunlimited.com/product/winchester-small-pistol-primers-1000-count/',
      # 'https://reloadingunlimited.com/product/winchester-small-rifle-primers-1000-count/',
      # 'https://reloadingunlimited.com/product/winchester-small-rifle-primers-5000-count/',
      # 'https://reloadingunlimited.com/product/winchester-usa-ready-small-pistol-match-primers-1000-count/',
      # 'https://reloadingunlimited.com/product/winchester-usa-ready-small-rifle-match-primers-1000-count/',
    ]
  },
  {
    # brunos
    keyword: 'Sorry, we are currently sold out',
    urls: [
      'https://www.brunoshooters.com/mm5/merchant.mvc?Screen=PROD&Page_Code=9084',
      'https://www.brunoshooters.com/mm5/merchant.mvc?Screen=PROD&Page_Code=9072',
      'https://www.brunoshooters.com/mm5/merchant.mvc?Screen=PROD&Page_Code=9074',
      'https://www.brunoshooters.com/mm5/merchant.mvc?Screen=PROD&Page_Code=9165',
      'https://www.brunoshooters.com/mm5/merchant.mvc?Screen=PROD&Page_Code=9070',
      'https://www.brunoshooters.com/mm5/merchant.mvc?Screen=PROD&Page_Code=9083',
      'https://www.brunoshooters.com/mm5/merchant.mvc?Screen=PROD&Page_Code=9144',
      'https://www.brunoshooters.com/mm5/merchant.mvc?Screen=PROD&Page_Code=10743',
      'https://www.brunoshooters.com/mm5/merchant.mvc?Screen=PROD&Page_Code=9089',
      'https://www.brunoshooters.com/mm5/merchant.mvc?Screen=PROD&Page_Code=14218',
      'https://www.brunoshooters.com/mm5/merchant.mvc?Screen=PROD&Page_Code=9077',
      'https://www.brunoshooters.com/mm5/merchant.mvc?Screen=PROD&Page_Code=15074',
      'https://www.brunoshooters.com/mm5/merchant.mvc?Screen=PROD&Page_Code=23',
      'https://www.brunoshooters.com/mm5/merchant.mvc?Screen=PROD&Page_Code=12914',
      'https://www.brunoshooters.com/mm5/merchant.mvc?Screen=PROD&Page_Code=12938',
    ]
  },

  {
    keyword: 'temporarily sold out',
    urls: [
      'https://www.sportsmans.com/shooting-gear-gun-supplies/reloading-equipment-supplies/primers/cci-no-500-small-pistol-primers-1000-count/p/304224',
      'https://www.sportsmans.com/shooting-gear-gun-supplies/reloading-equipment-supplies/primers/cci-no-400-small-rifle-primers-1000-count/p/304222',
      'https://www.sportsmans.com/shooting-gear-gun-supplies/reloading-equipment-supplies/primers/cci-br4-small-rifle-primers-100-count/p/304266',
      'https://www.sportsmans.com/shooting-gear-gun-supplies/reloading-equipment-supplies/primers/cci-no-500-small-pistol-primers-100-count/p/304263',
      'https://www.sportsmans.com/shooting-gear-gun-supplies/reloading-equipment-supplies/primers/cci-no-400-small-rifle-primer-100-count/p/304261',
      'https://www.sportsmans.com/shooting-gear-gun-supplies/reloading-equipment-supplies/primers/federal-premium-no-205-small-rifle-primers-1000-count/p/306955',
      'https://www.sportsmans.com/shooting-gear-gun-supplies/reloading-equipment-supplies/primers/federal-premium-no-100-small-pistol-primers-1000-count/p/306946',
      'https://www.sportsmans.com/shooting-gear-gun-supplies/reloading-equipment-supplies/primers/federal-champion-no-205-small-rifle-primers-100-count/p/307958',
      'https://www.sportsmans.com/shooting-gear-gun-supplies/reloading-equipment-supplies/primers/cci-no-450-small-magnum-rifle-primers-1000-count/p/304223',
      'https://www.sportsmans.com/shooting-gear-gun-supplies/reloading-equipment-supplies/primers/winchester-no-6-12-small-rifle-primers-100-count/p/307655',
      'https://www.sportsmans.com/shooting-gear-gun-supplies/reloading-equipment-supplies/primers/winchester-no-6-12-small-rifle-primers-100-count/p/307655',
      'https://www.sportsmans.com/shooting-gear-gun-supplies/reloading-equipment-supplies/primers/winchester-no-6-12-small-rifle-primers-1000-count/p/308113',
      'https://www.sportsmans.com/shooting-gear-gun-supplies/reloading-equipment-supplies/primers/cci-no-br4-small-rifle-bench-rest-primers-1000-count/p/304227',
      'https://www.sportsmans.com/shooting-gear-gun-supplies/reloading-equipment-supplies/primers/remington-no-6-12-small-rifle-primers-1000-count/p/1114418',
      'https://www.sportsmans.com/shooting-gear-gun-supplies/reloading-equipment-supplies/primers/remington-no-6-12-small-rifle-primers-100-count/p/1110115',
      'https://www.sportsmans.com/shooting-gear-gun-supplies/reloading-equipment-supplies/primers/federal-gold-medal-small-rifle-match-primers-1000-count/p/306989',
      'https://www.sportsmans.com/shooting-gear-gun-supplies/reloading-equipment-supplies/primers/winchester-no-1-12-small-regular-pistol-primer-100-count/p/307653',
      'https://www.sportsmans.com/shooting-gear-gun-supplies/reloading-equipment-supplies/primers/federal-gold-medal-no-100m-small-pistol-match-primers-100-count/p/307965',
      'https://www.sportsmans.com/shooting-gear-gun-supplies/reloading-equipment-supplies/primers/remington-boxer-no-1-12-small-pistol-primers-100-count/p/1110110',
    ]
  },
]
